import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "./Components/Nav/MainNav";

// This is the root layout file for the Next.js application. It contains pregenerated code by Next.js when creating a new app
// such as fonts, metadata, and the main layout structure. I just edited it to provide a very basic main nav bar.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* This is the main navigation bar that will be displayed on all pages since it's inside the layout file */}
        <MainNav />
        {children}
      </body>
    </html>
  );
}
